// export const type = 'type/name'

export const GET_CHARACTER_FETCH = "CHARACTER/GET_CHARACTER_FETCH";
export const GET_CHARACTER_SUCCESS = "CHARACTER/GET_CHARACTER_SUCCESS";
export const GET_CHARACTER_ERROR = "CHARACTER/GET_CHARACTER_ERROR";

export const SET_CURRENT_CHAR = "CHARACTER/SET_CURRENT_CHAR";

export const ADD_TO_FAVORITE = "CHARACTER/ADD_TO_FAVORITE";
export const DELETE_FROM_FAVORITE = "CHARACTER/DELETE_FROM_FAVORITE";
export const GET_FAVORITES_FETCH = "CHARACTER/GET_FAVORITES_FETCH";
export const GET_FAVORITES_SUCCESS = "CHARACTER/GET_FAVORITES_SUCCESS";
export const GET_FAVORITES_ERROR = "CHARACTER/GET_FAVORITES_ERROR";
