// export const TYPE = 'TYPE/NAME'

export const LOGIN_GOOGLE_FETCH = "USER/LOGIN_GOOGLE_FETCH";
export const LOGIN_GOOGLE_SUCCESS = "USER/LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_ERROR = "USER/LOGIN_GOOGLE_ERROR";
export const END_SESSION = "USER/END_SESSION";
export const RESTORE_SESSION = "USER/RESTORE_SESSION";
